-- =====================================================================
-- CSU MARKETPLACE - ANALYTICS FUNCTIONS, INDEXES & TRIGGERS
-- Part 2: Helper Functions, Performance Indexes, Data Integrity Triggers
-- Version: 1.0 Production
-- Date: November 14, 2025
-- =====================================================================

-- =====================================================================
-- SECTION 5: HELPER FUNCTIONS
-- Purpose: Reusable metric calculations and business logic
-- =====================================================================

-- Function: Calculate User Engagement Score
-- Returns: Engagement score (0-100) based on user activity
CREATE OR REPLACE FUNCTION fn_user_engagement_score(p_user_id UUID)
RETURNS DECIMAL(5, 2) AS $$
DECLARE
    v_score DECIMAL(5, 2) := 0;
    v_products_weight DECIMAL := 20;
    v_sales_weight DECIMAL := 30;
    v_orders_weight DECIMAL := 20;
    v_rating_weight DECIMAL := 20;
    v_activity_weight DECIMAL := 10;
BEGIN
    -- Products posted (max 20 points, capped at 10 products)
    v_score := v_score + LEAST((SELECT total_products_posted FROM users WHERE user_id = p_user_id) * 2, v_products_weight);
    
    -- Sales completed (max 30 points, capped at 15 sales)
    v_score := v_score + LEAST((SELECT total_products_sold FROM users WHERE user_id = p_user_id) * 2, v_sales_weight);
    
    -- Orders as buyer (max 20 points, capped at 10 orders)
    v_score := v_score + LEAST((SELECT total_orders_as_buyer FROM users WHERE user_id = p_user_id) * 2, v_orders_weight);
    
    -- Seller rating (max 20 points)
    v_score := v_score + ((SELECT average_seller_rating FROM users WHERE user_id = p_user_id) / 5 * v_rating_weight);
    
    -- Recent activity (max 10 points, based on days since last active)
    v_score := v_score + GREATEST(v_activity_weight - (SELECT EXTRACT(DAY FROM NOW() - COALESCE(last_active_at, created_at)) FROM users WHERE user_id = p_user_id), 0);
    
    RETURN LEAST(v_score, 100);
END;
$$ LANGUAGE plpgsql STABLE;

COMMENT ON FUNCTION fn_user_engagement_score IS 'Calculate user engagement score (0-100) based on activity metrics';

-- Function: Get Category Revenue Share
-- Returns: Percentage of total platform revenue
CREATE OR REPLACE FUNCTION fn_category_revenue_share(p_category_id INTEGER)
RETURNS DECIMAL(5, 2) AS $$
DECLARE
    v_category_revenue DECIMAL(12, 2);
    v_total_revenue DECIMAL(12, 2);
BEGIN
    SELECT COALESCE(SUM(item_price * quantity), 0) 
    INTO v_category_revenue
    FROM transactions 
    WHERE category_id = p_category_id AND transaction_status = 'COMPLETED';
    
    SELECT COALESCE(SUM(item_price * quantity), 0) 
    INTO v_total_revenue
    FROM transactions 
    WHERE transaction_status = 'COMPLETED';
    
    IF v_total_revenue = 0 THEN
        RETURN 0;
    END IF;
    
    RETURN ROUND((v_category_revenue / v_total_revenue) * 100, 2);
END;
$$ LANGUAGE plpgsql STABLE;

COMMENT ON FUNCTION fn_category_revenue_share IS 'Calculate category revenue as percentage of total platform revenue';

-- Function: Calculate Product Conversion Rate
-- Returns: Percentage of views that resulted in transactions
CREATE OR REPLACE FUNCTION fn_product_conversion_rate(p_product_id INTEGER)
RETURNS DECIMAL(5, 2) AS $$
DECLARE
    v_views INTEGER;
    v_sales INTEGER;
BEGIN
    SELECT view_count INTO v_views FROM products WHERE product_id = p_product_id;
    
    SELECT COUNT(*) INTO v_sales 
    FROM transactions 
    WHERE product_id = p_product_id AND transaction_status = 'COMPLETED';
    
    IF v_views = 0 THEN
        RETURN 0;
    END IF;
    
    RETURN ROUND((v_sales::DECIMAL / v_views) * 100, 2);
END;
$$ LANGUAGE plpgsql STABLE;

COMMENT ON FUNCTION fn_product_conversion_rate IS 'Calculate product conversion rate (sales/views * 100)';

-- Function: Get Seller Response Time (Average)
-- Returns: Average hours to accept/reject orders
CREATE OR REPLACE FUNCTION fn_seller_avg_response_time(p_seller_id UUID)
RETURNS DECIMAL(10, 2) AS $$
DECLARE
    v_avg_hours DECIMAL(10, 2);
BEGIN
    SELECT AVG(EXTRACT(EPOCH FROM (updated_at - created_at))/3600)
    INTO v_avg_hours
    FROM order_details
    WHERE seller_id = p_seller_id 
    AND order_status IN ('accepted', 'rejected')
    AND updated_at > created_at;
    
    RETURN COALESCE(v_avg_hours, 0);
END;
$$ LANGUAGE plpgsql STABLE;

COMMENT ON FUNCTION fn_seller_avg_response_time IS 'Calculate average seller response time in hours';

-- Function: Get User Lifetime Value (CLV)
-- Returns: Total value generated by user (buyer + seller)
CREATE OR REPLACE FUNCTION fn_user_lifetime_value(p_user_id UUID)
RETURNS DECIMAL(12, 2) AS $$
DECLARE
    v_seller_value DECIMAL(12, 2);
    v_buyer_value DECIMAL(12, 2);
BEGIN
    -- Revenue as seller
    SELECT COALESCE(SUM(item_price * quantity), 0)
    INTO v_seller_value
    FROM transactions
    WHERE seller_id = p_user_id AND transaction_status = 'COMPLETED';
    
    -- Spending as buyer
    SELECT COALESCE(SUM(item_price * quantity), 0)
    INTO v_buyer_value
    FROM transactions
    WHERE buyer_id = p_user_id AND transaction_status = 'COMPLETED';
    
    RETURN v_seller_value + v_buyer_value;
END;
$$ LANGUAGE plpgsql STABLE;

COMMENT ON FUNCTION fn_user_lifetime_value IS 'Calculate total user lifetime value (CLV) as buyer + seller';

-- Function: Get Platform Health Score
-- Returns: Overall platform health (0-100)
CREATE OR REPLACE FUNCTION fn_platform_health_score()
RETURNS DECIMAL(5, 2) AS $$
DECLARE
    v_score DECIMAL(5, 2) := 0;
    v_user_growth DECIMAL;
    v_transaction_growth DECIMAL;
    v_avg_rating DECIMAL;
    v_pending_ratio DECIMAL;
BEGIN
    -- User growth (20 points) - comparing last 7 days to previous 7 days
    SELECT CASE 
        WHEN prev_count > 0 THEN 
            LEAST((curr_count::DECIMAL / prev_count - 1) * 100, 20)
        ELSE 20
    END INTO v_user_growth
    FROM (
        SELECT 
            (SELECT COUNT(*) FROM users WHERE created_at >= NOW() - INTERVAL '7 days') as curr_count,
            (SELECT COUNT(*) FROM users WHERE created_at >= NOW() - INTERVAL '14 days' AND created_at < NOW() - INTERVAL '7 days') as prev_count
    ) growth;
    
    -- Transaction growth (30 points)
    SELECT CASE 
        WHEN prev_count > 0 THEN 
            LEAST((curr_count::DECIMAL / prev_count - 1) * 100, 30)
        ELSE 30
    END INTO v_transaction_growth
    FROM (
        SELECT 
            (SELECT COUNT(*) FROM transactions WHERE created_at >= NOW() - INTERVAL '7 days' AND transaction_status = 'COMPLETED') as curr_count,
            (SELECT COUNT(*) FROM transactions WHERE created_at >= NOW() - INTERVAL '14 days' AND created_at < NOW() - INTERVAL '7 days' AND transaction_status = 'COMPLETED') as prev_count
    ) tx_growth;
    
    -- Average platform rating (30 points)
    SELECT COALESCE(AVG(rating) / 5 * 30, 0) INTO v_avg_rating FROM reviews;
    
    -- Pending approval ratio (20 points) - lower is better
    SELECT 20 - LEAST((SELECT COUNT(*) FROM products WHERE status = 'PENDING')::DECIMAL / NULLIF((SELECT COUNT(*) FROM products), 0) * 100, 20)
    INTO v_pending_ratio;
    
    v_score := GREATEST(v_user_growth, 0) + GREATEST(v_transaction_growth, 0) + v_avg_rating + COALESCE(v_pending_ratio, 0);
    
    RETURN LEAST(v_score, 100);
END;
$$ LANGUAGE plpgsql STABLE;

COMMENT ON FUNCTION fn_platform_health_score IS 'Calculate overall platform health score (0-100) based on growth and engagement';

-- Function: Get Top Category for User
-- Returns: User's most active category
CREATE OR REPLACE FUNCTION fn_user_top_category(p_user_id UUID)
RETURNS TABLE (
    category_id INTEGER,
    category_name VARCHAR(100),
    product_count BIGINT
) AS $$
BEGIN
    RETURN QUERY
    SELECT 
        c.category_id,
        c.category_name,
        COUNT(p.product_id) as product_count
    FROM products p
    INNER JOIN categories c ON p.category_id = c.category_id
    WHERE p.user_id = p_user_id
    GROUP BY c.category_id, c.category_name
    ORDER BY product_count DESC
    LIMIT 1;
END;
$$ LANGUAGE plpgsql STABLE;

COMMENT ON FUNCTION fn_user_top_category IS 'Get user''s most active category by product count';

-- Function: Calculate Churn Risk Score
-- Returns: Churn risk (0-100, higher = more risk)
CREATE OR REPLACE FUNCTION fn_user_churn_risk(p_user_id UUID)
RETURNS DECIMAL(5, 2) AS $$
DECLARE
    v_days_inactive INTEGER;
    v_engagement_score DECIMAL(5, 2);
    v_churn_score DECIMAL(5, 2) := 0;
BEGIN
    SELECT EXTRACT(DAY FROM NOW() - COALESCE(last_active_at, created_at))
    INTO v_days_inactive
    FROM users WHERE user_id = p_user_id;
    
    v_engagement_score := fn_user_engagement_score(p_user_id);
    
    -- Inactivity component (0-50 points)
    v_churn_score := LEAST(v_days_inactive * 2, 50);
    
    -- Low engagement component (0-50 points)
    v_churn_score := v_churn_score + (50 - (v_engagement_score / 2));
    
    RETURN LEAST(v_churn_score, 100);
END;
$$ LANGUAGE plpgsql STABLE;

COMMENT ON FUNCTION fn_user_churn_risk IS 'Calculate user churn risk score (0-100, higher = more likely to churn)';

-- Function: Get Revenue Forecast (Simple Linear)
-- Returns: Projected revenue for next N days
CREATE OR REPLACE FUNCTION fn_revenue_forecast(p_days_ahead INTEGER DEFAULT 30)
RETURNS DECIMAL(12, 2) AS $$
DECLARE
    v_avg_daily_revenue DECIMAL(12, 2);
    v_growth_rate DECIMAL(5, 4);
BEGIN
    -- Calculate average daily revenue over last 30 days
    SELECT COALESCE(AVG(daily_revenue), 0)
    INTO v_avg_daily_revenue
    FROM (
        SELECT 
            DATE(completed_at) as date,
            SUM(item_price * quantity) as daily_revenue
        FROM transactions
        WHERE transaction_status = 'COMPLETED'
        AND completed_at >= NOW() - INTERVAL '30 days'
        GROUP BY DATE(completed_at)
    ) daily_rev;
    
    -- Simple growth rate calculation (last 7 days vs previous 7 days)
    SELECT CASE 
        WHEN prev_rev > 0 THEN (curr_rev / prev_rev - 1)
        ELSE 0
    END INTO v_growth_rate
    FROM (
        SELECT 
            (SELECT COALESCE(SUM(item_price * quantity), 0) FROM transactions WHERE transaction_status = 'COMPLETED' AND completed_at >= NOW() - INTERVAL '7 days') as curr_rev,
            (SELECT COALESCE(SUM(item_price * quantity), 0) FROM transactions WHERE transaction_status = 'COMPLETED' AND completed_at >= NOW() - INTERVAL '14 days' AND completed_at < NOW() - INTERVAL '7 days') as prev_rev
    ) growth_calc;
    
    -- Apply compound growth
    RETURN v_avg_daily_revenue * p_days_ahead * (1 + v_growth_rate);
END;
$$ LANGUAGE plpgsql STABLE;

COMMENT ON FUNCTION fn_revenue_forecast IS 'Forecast revenue for next N days using linear projection with growth rate';

-- Function: Get Admin Dashboard Summary
-- Returns: Comprehensive admin metrics in one call
CREATE OR REPLACE FUNCTION fn_admin_dashboard_summary()
RETURNS TABLE (
    metric_name VARCHAR(100),
    metric_value DECIMAL(12, 2),
    metric_label VARCHAR(50)
) AS $$
BEGIN
    RETURN QUERY
    SELECT 'total_users'::VARCHAR(100), (SELECT COUNT(*)::DECIMAL FROM users), 'users'::VARCHAR(50)
    UNION ALL
    SELECT 'active_users_7d', (SELECT COUNT(*)::DECIMAL FROM users WHERE last_active_at >= NOW() - INTERVAL '7 days'), 'users'
    UNION ALL
    SELECT 'total_products', (SELECT COUNT(*)::DECIMAL FROM products), 'products'
    UNION ALL
    SELECT 'active_listings', (SELECT COUNT(*)::DECIMAL FROM products WHERE status = 'APPROVED' AND is_available = TRUE), 'products'
    UNION ALL
    SELECT 'pending_approvals', (SELECT COUNT(*)::DECIMAL FROM products WHERE status = 'PENDING'), 'products'
    UNION ALL
    SELECT 'total_transactions', (SELECT COUNT(*)::DECIMAL FROM transactions), 'transactions'
    UNION ALL
    SELECT 'completed_transactions', (SELECT COUNT(*)::DECIMAL FROM transactions WHERE transaction_status = 'COMPLETED'), 'transactions'
    UNION ALL
    SELECT 'total_revenue', (SELECT COALESCE(SUM(item_price * quantity), 0) FROM transactions WHERE transaction_status = 'COMPLETED'), 'currency'
    UNION ALL
    SELECT 'revenue_30d', (SELECT COALESCE(SUM(item_price * quantity), 0) FROM transactions WHERE transaction_status = 'COMPLETED' AND completed_at >= NOW() - INTERVAL '30 days'), 'currency'
    UNION ALL
    SELECT 'platform_health', fn_platform_health_score(), 'percentage';
END;
$$ LANGUAGE plpgsql STABLE;

COMMENT ON FUNCTION fn_admin_dashboard_summary IS 'Get all admin dashboard KPIs in a single function call';

-- =====================================================================
-- SECTION 6: PERFORMANCE INDEXES
-- Purpose: Optimize analytics queries, searches, filters, and sorting
-- =====================================================================

-- Transaction Analytics Indexes
CREATE INDEX IF NOT EXISTS idx_transactions_completed_at_status 
    ON transactions(completed_at DESC, transaction_status) 
    WHERE transaction_status = 'COMPLETED';

CREATE INDEX IF NOT EXISTS idx_transactions_category_revenue 
    ON transactions(category_id, item_price, quantity) 
    WHERE transaction_status = 'COMPLETED';

CREATE INDEX IF NOT EXISTS idx_transactions_date_range 
    ON transactions(completed_at, transaction_status);

CREATE INDEX IF NOT EXISTS idx_transactions_seller_revenue 
    ON transactions(seller_id, item_price, quantity) 
    WHERE transaction_status = 'COMPLETED';

CREATE INDEX IF NOT EXISTS idx_transactions_buyer_spending 
    ON transactions(buyer_id, item_price, quantity) 
    WHERE transaction_status = 'COMPLETED';

-- Product Performance Indexes
CREATE INDEX IF NOT EXISTS idx_products_category_active 
    ON products(category_id, status, is_available) 
    WHERE status = 'APPROVED' AND is_available = TRUE;

CREATE INDEX IF NOT EXISTS idx_products_user_status 
    ON products(user_id, status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_products_view_count 
    ON products(view_count DESC) 
    WHERE status = 'APPROVED';

CREATE INDEX IF NOT EXISTS idx_products_price_range 
    ON products(price, category_id) 
    WHERE status = 'APPROVED' AND is_available = TRUE;

CREATE INDEX IF NOT EXISTS idx_products_listing_type_status 
    ON products(listing_type, status, is_available);

CREATE INDEX IF NOT EXISTS idx_products_created_date 
    ON products(created_at, status);

-- User Analytics Indexes
CREATE INDEX IF NOT EXISTS idx_users_activity_status 
    ON users(last_active_at DESC, is_active) 
    WHERE is_active = TRUE;

CREATE INDEX IF NOT EXISTS idx_users_revenue_ranking 
    ON users(total_revenue DESC) 
    WHERE total_revenue > 0;

CREATE INDEX IF NOT EXISTS idx_users_seller_rating 
    ON users(average_seller_rating DESC, total_reviews_received) 
    WHERE total_products_sold > 0;

CREATE INDEX IF NOT EXISTS idx_users_department_active 
    ON users(department, is_active) 
    WHERE is_active = TRUE;

CREATE INDEX IF NOT EXISTS idx_users_registration_date 
    ON users(created_at);

-- Order Details Indexes
CREATE INDEX IF NOT EXISTS idx_orders_buyer_status_date 
    ON order_details(buyer_id, order_status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_orders_seller_status_date 
    ON order_details(seller_id, order_status, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_orders_product_status 
    ON order_details(product_id, order_status);

CREATE INDEX IF NOT EXISTS idx_orders_date_range 
    ON order_details(created_at, order_status);

-- Product Favorites Indexes
CREATE INDEX IF NOT EXISTS idx_favorites_product_count 
    ON product_favorites(product_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_favorites_user_date 
    ON product_favorites(user_id, created_at DESC);

-- Review Indexes
CREATE INDEX IF NOT EXISTS idx_reviews_seller_rating 
    ON reviews(seller_id, rating, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_reviews_product_rating 
    ON reviews(product_id, rating) 
    WHERE product_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_reviews_date 
    ON reviews(created_at);

-- Category Indexes (already have basic indexes, adding analytics-focused ones)
CREATE INDEX IF NOT EXISTS idx_categories_product_count 
    ON categories(total_products DESC);

CREATE INDEX IF NOT EXISTS idx_categories_views 
    ON categories(total_views DESC);

-- Composite Indexes for Common Queries
CREATE INDEX IF NOT EXISTS idx_products_category_price_status 
    ON products(category_id, price, status, is_available);

CREATE INDEX IF NOT EXISTS idx_transactions_seller_buyer_status 
    ON transactions(seller_id, buyer_id, transaction_status, created_at DESC);

-- Full-Text Search Indexes (for product search)
CREATE INDEX IF NOT EXISTS idx_products_name_search 
    ON products USING gin(to_tsvector('english', product_name));

CREATE INDEX IF NOT EXISTS idx_products_description_search 
    ON products USING gin(to_tsvector('english', description));

-- =====================================================================
-- SECTION 7: DATA INTEGRITY & ANALYTICS TRIGGERS
-- Purpose: Maintain materialized views, log changes, track metrics
-- =====================================================================

-- Trigger: Auto-refresh materialized views on transaction completion
CREATE OR REPLACE FUNCTION trigger_refresh_analytics_on_transaction()
RETURNS TRIGGER AS $$
BEGIN
    -- Only refresh if transaction status changed to COMPLETED
    IF NEW.transaction_status = 'COMPLETED' AND OLD.transaction_status != 'COMPLETED' THEN
        -- Refresh materialized views (use CONCURRENTLY to avoid locks)
        REFRESH MATERIALIZED VIEW CONCURRENTLY mv_daily_platform_metrics;
        REFRESH MATERIALIZED VIEW CONCURRENTLY mv_transaction_funnel;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER transaction_completed_refresh_analytics
    AFTER UPDATE ON transactions
    FOR EACH ROW
    WHEN (NEW.transaction_status = 'COMPLETED' AND OLD.transaction_status IS DISTINCT FROM 'COMPLETED')
    EXECUTE FUNCTION trigger_refresh_analytics_on_transaction();

COMMENT ON TRIGGER transaction_completed_refresh_analytics ON transactions IS 
    'Auto-refresh analytics materialized views when transaction completes';

-- Trigger: Increment product view count with deduplication
CREATE OR REPLACE FUNCTION trigger_increment_product_views()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE products 
    SET view_count = view_count + 1 
    WHERE product_id = NEW.product_id;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Note: This would be triggered by application logic when a user views a product
-- Uncomment if you want database-level view tracking:
-- CREATE TRIGGER product_view_tracking
--     AFTER INSERT ON product_views_log  -- You'd need to create this table
--     FOR EACH ROW
--     EXECUTE FUNCTION trigger_increment_product_views();

-- Trigger: Update category view count
CREATE OR REPLACE FUNCTION trigger_update_category_views()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.view_count > OLD.view_count THEN
        UPDATE categories 
        SET total_views = total_views + (NEW.view_count - OLD.view_count)
        WHERE category_id = NEW.category_id;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER product_view_update_category
    AFTER UPDATE OF view_count ON products
    FOR EACH ROW
    WHEN (NEW.view_count > OLD.view_count)
    EXECUTE FUNCTION trigger_update_category_views();

COMMENT ON TRIGGER product_view_update_category ON products IS 
    'Sync product view count to category total_views';

-- Trigger: Log admin actions
CREATE OR REPLACE FUNCTION trigger_log_admin_action()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.status != OLD.status THEN
        INSERT INTO admin_logs (admin_id, action, target_product, description)
        VALUES (
            NEW.approved_by,
            'PRODUCT_STATUS_CHANGE',
            NEW.product_id,
            'Changed status from ' || OLD.status || ' to ' || NEW.status
        );
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER product_status_change_log
    AFTER UPDATE OF status ON products
    FOR EACH ROW
    WHEN (NEW.status IS DISTINCT FROM OLD.status AND NEW.approved_by IS NOT NULL)
    EXECUTE FUNCTION trigger_log_admin_action();

COMMENT ON TRIGGER product_status_change_log ON products IS 
    'Log product approval/rejection actions to admin_logs';

-- Trigger: Maintain seller performance cache
CREATE OR REPLACE FUNCTION trigger_update_seller_cache()
RETURNS TRIGGER AS $$
BEGIN
    -- This would update a hypothetical seller_performance_cache table
    -- Useful for very high-traffic platforms
    -- Implementation depends on your caching strategy
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger: Detect and flag suspicious activity
CREATE OR REPLACE FUNCTION trigger_detect_suspicious_activity()
RETURNS TRIGGER AS $$
DECLARE
    v_rapid_orders INTEGER;
BEGIN
    -- Check for rapid order creation (more than 10 in 1 minute)
    SELECT COUNT(*) INTO v_rapid_orders
    FROM order_details
    WHERE buyer_id = NEW.buyer_id
    AND created_at >= NOW() - INTERVAL '1 minute';
    
    IF v_rapid_orders > 10 THEN
        -- Log suspicious activity
        INSERT INTO admin_logs (admin_id, action, target_user, description)
        VALUES (
            NULL,
            'SUSPICIOUS_ACTIVITY',
            NEW.buyer_id,
            'Rapid order creation: ' || v_rapid_orders || ' orders in 1 minute'
        );
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER detect_rapid_orders
    AFTER INSERT ON order_details
    FOR EACH ROW
    EXECUTE FUNCTION trigger_detect_suspicious_activity();

COMMENT ON TRIGGER detect_rapid_orders ON order_details IS 
    'Detect and log suspicious rapid order creation patterns';

-- =====================================================================
-- SECTION 8: SCHEDULED REFRESH FUNCTION
-- Purpose: Automated materialized view refresh via cron/pg_cron
-- =====================================================================

-- Function: Refresh dashboard materialized views (scheduled task)
CREATE OR REPLACE FUNCTION fn_scheduled_analytics_refresh()
RETURNS TEXT AS $$
DECLARE
    v_start_time TIMESTAMPTZ := NOW();
    v_result TEXT;
BEGIN
    -- Refresh all materialized views concurrently
    REFRESH MATERIALIZED VIEW CONCURRENTLY mv_daily_platform_metrics;
    REFRESH MATERIALIZED VIEW CONCURRENTLY mv_weekly_revenue_by_category;
    REFRESH MATERIALIZED VIEW CONCURRENTLY mv_user_engagement_heatmap;
    REFRESH MATERIALIZED VIEW CONCURRENTLY mv_monthly_category_pareto;
    REFRESH MATERIALIZED VIEW CONCURRENTLY mv_transaction_funnel;
    REFRESH MATERIALIZED VIEW CONCURRENTLY mv_seller_performance_scorecard;
    REFRESH MATERIALIZED VIEW CONCURRENTLY mv_product_lifecycle_analysis;
    
    v_result := 'Analytics refresh completed in ' || 
                EXTRACT(EPOCH FROM (NOW() - v_start_time))::TEXT || ' seconds';
    
    RETURN v_result;
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION fn_scheduled_analytics_refresh IS 
    'Refresh all analytics materialized views - Schedule with pg_cron: 
     SELECT cron.schedule(''refresh-analytics'', ''0 */6 * * *'', ''SELECT fn_scheduled_analytics_refresh()'');';

-- =====================================================================
-- SECTION 9: UTILITY FUNCTIONS FOR DASHBOARD INTEGRATION
-- Purpose: Helper functions for frontend data fetching
-- =====================================================================

-- Function: Get chart data in JSON format
CREATE OR REPLACE FUNCTION fn_get_chart_data(p_chart_type VARCHAR(50), p_date_range INTEGER DEFAULT 30)
RETURNS JSONB AS $$
BEGIN
    CASE p_chart_type
        WHEN 'revenue_trend' THEN
            RETURN (
                SELECT jsonb_agg(row_to_json(t))
                FROM (
                    SELECT date, daily_revenue, cumulative_revenue
                    FROM analytics_view_revenue_trend
                    WHERE date >= CURRENT_DATE - p_date_range
                    ORDER BY date ASC
                ) t
            );
        
        WHEN 'category_performance' THEN
            RETURN (
                SELECT jsonb_agg(row_to_json(t))
                FROM (
                    SELECT category_name, total_revenue, completed_transactions
                    FROM analytics_view_category_performance
                    ORDER BY total_revenue DESC
                    LIMIT 10
                ) t
            );
        
        WHEN 'transaction_status' THEN
            RETURN (
                SELECT jsonb_agg(row_to_json(t))
                FROM analytics_view_transaction_status t
            );
        
        ELSE
            RETURN '{"error": "Unknown chart type"}'::JSONB;
    END CASE;
END;
$$ LANGUAGE plpgsql STABLE;

COMMENT ON FUNCTION fn_get_chart_data IS 
    'Get pre-formatted JSON data for frontend charts. Usage: SELECT fn_get_chart_data(''revenue_trend'', 30)';

-- =====================================================================
-- COMPLETION MESSAGE & USAGE GUIDE
-- =====================================================================

DO $$
BEGIN
    RAISE NOTICE '========================================================';
    RAISE NOTICE 'ANALYTICS FUNCTIONS, INDEXES & TRIGGERS CREATED';
    RAISE NOTICE '========================================================';
    RAISE NOTICE 'Helper Functions: 11';
    RAISE NOTICE 'Performance Indexes: 30+';
    RAISE NOTICE 'Triggers: 6';
    RAISE NOTICE '';
    RAISE NOTICE 'RECOMMENDED REFRESH SCHEDULE (using pg_cron):';
    RAISE NOTICE '------------------------------------------------';
    RAISE NOTICE 'Every 6 hours:  SELECT fn_scheduled_analytics_refresh();';
    RAISE NOTICE 'Daily at 1 AM:  REFRESH MATERIALIZED VIEW mv_seller_performance_scorecard;';
    RAISE NOTICE '';
    RAISE NOTICE 'MANUAL REFRESH:';
    RAISE NOTICE '------------------------------------------------';
    RAISE NOTICE 'SELECT refresh_all_analytics_mv();';
    RAISE NOTICE '';
    RAISE NOTICE 'CHART DATA EXAMPLES:';
    RAISE NOTICE '------------------------------------------------';
    RAISE NOTICE 'SELECT fn_get_chart_data(''revenue_trend'', 30);';
    RAISE NOTICE 'SELECT * FROM analytics_view_category_performance;';
    RAISE NOTICE 'SELECT * FROM mv_transaction_funnel;';
    RAISE NOTICE '';
    RAISE NOTICE 'Status: ✅ All Analytics Components Ready';
    RAISE NOTICE '========================================================';
END $$;

-- =====================================================================
-- ORDER MANAGEMENT FUNCTIONS
-- Purpose: Accept and Reject Orders with Blockchain Transaction Creation
-- =====================================================================

-- Function: Accept Order and Create Transaction
CREATE OR REPLACE FUNCTION accept_order_and_create_transaction(
    p_order_id UUID,
    p_seller_final_pickup_location TEXT DEFAULT NULL,
    p_seller_final_meetup_location TEXT DEFAULT NULL
)
RETURNS UUID AS $$
DECLARE
    v_transaction_id UUID;
    v_order RECORD;
    v_buyer RECORD;
    v_seller RECORD;
    v_category RECORD;
BEGIN
    -- Get order details
    SELECT * INTO v_order
    FROM order_details
    WHERE order_id = p_order_id AND order_status = 'pending';
    
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Order not found or already processed';
    END IF;
    
    -- Get buyer information
    SELECT user_id, first_name, last_name, email, phone_number 
    INTO v_buyer
    FROM users
    WHERE user_id = v_order.buyer_id;
    
    -- Get seller information
    SELECT user_id, first_name, last_name, email, phone_number 
    INTO v_seller
    FROM users
    WHERE user_id = v_order.seller_id;
    
    -- Get category information
    SELECT cat.category_id, cat.category_name 
    INTO v_category
    FROM categories cat
    INNER JOIN products p ON cat.category_id = p.category_id
    WHERE p.product_id = v_order.product_id;
    
    -- Update order status to accepted
    UPDATE order_details
    SET 
        order_status = 'accepted',
        final_pickup_location = COALESCE(p_seller_final_pickup_location, pickup_location),
        final_meetup_location = COALESCE(p_seller_final_meetup_location, meetup_location),
        updated_at = NOW()
    WHERE order_id = p_order_id;
    
    -- Create transaction record for blockchain
    INSERT INTO transactions (
        order_id,
        buyer_id,
        seller_id,
        product_id,
        category_id,
        buyer_name,
        seller_name,
        seller_phone,
        listing_type,
        category_name,
        item_name,
        item_description,
        item_price,
        quantity,
        final_pickup_location,
        final_meetup_location,
        return_condition,
        rental_duration,
        start_date,
        end_date,
        service_schedule,
        service_duration,
        message_to_seller,
        transaction_status,
        is_blockchain_pending,
        accepted_at,
        blockchain_tx_hash
    ) VALUES (
        p_order_id,
        v_order.buyer_id,
        v_order.seller_id,
        v_order.product_id,
        v_category.category_id,
        COALESCE(v_buyer.first_name || ' ' || v_buyer.last_name, 'Buyer'),
        COALESCE(v_seller.first_name || ' ' || v_seller.last_name, 'Seller'),
        v_seller.phone_number,
        v_order.listing_type,
        v_category.category_name,
        v_order.product_name,
        v_order.description,
        v_order.price,
        v_order.buyer_quantity,
        COALESCE(p_seller_final_pickup_location, v_order.pickup_location),
        COALESCE(p_seller_final_meetup_location, v_order.meetup_location),
        v_order.return_condition,
        v_order.rental_duration,
        v_order.start_date,
        v_order.end_date,
        v_order.service_schedule,
        v_order.service_duration,
        v_order.message_to_seller,
        'PENDING',
        TRUE,
        NOW(),
        gen_random_uuid()::TEXT
    ) RETURNING transaction_id INTO v_transaction_id;
    
    -- Create notification for buyer
    INSERT INTO notifications (user_id, title, message, type, related_order_id, related_transaction_id, created_at)
    VALUES (
        v_order.buyer_id,
        'Order Accepted',
        'Your order for ' || v_order.product_name || ' has been accepted! Transaction is being processed on blockchain.',
        'transaction',
        p_order_id,
        v_transaction_id,
        NOW()
    );
    
    RETURN v_transaction_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION accept_order_and_create_transaction IS 
    'Accept a pending order and create transaction record for blockchain processing';

-- Function: Reject Order and Create Transaction
CREATE OR REPLACE FUNCTION reject_order(
    p_order_id UUID,
    p_rejection_reason TEXT DEFAULT NULL
)
RETURNS UUID AS $$
DECLARE
    v_transaction_id UUID;
    v_order RECORD;
    v_buyer RECORD;
    v_seller RECORD;
    v_category RECORD;
BEGIN
    -- Get order details
    SELECT * INTO v_order
    FROM order_details
    WHERE order_id = p_order_id AND order_status = 'pending';
    
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Order not found or already processed';
    END IF;
    
    -- Get buyer information
    SELECT user_id, first_name, last_name, email, phone_number 
    INTO v_buyer
    FROM users
    WHERE user_id = v_order.buyer_id;
    
    -- Get seller information
    SELECT user_id, first_name, last_name, email, phone_number 
    INTO v_seller
    FROM users
    WHERE user_id = v_order.seller_id;
    
    -- Get category information
    SELECT cat.category_id, cat.category_name 
    INTO v_category
    FROM categories cat
    INNER JOIN products p ON cat.category_id = p.category_id
    WHERE p.product_id = v_order.product_id;
    
    -- Update order status to rejected
    UPDATE order_details
    SET 
        order_status = 'rejected',
        rejection_reason = p_rejection_reason,
        updated_at = NOW()
    WHERE order_id = p_order_id;
    
    -- Create transaction record for blockchain as rejected
    INSERT INTO transactions (
        order_id,
        buyer_id,
        seller_id,
        product_id,
        category_id,
        buyer_name,
        seller_name,
        seller_phone,
        listing_type,
        category_name,
        item_name,
        item_description,
        item_price,
        quantity,
        final_pickup_location,
        final_meetup_location,
        return_condition,
        rental_duration,
        start_date,
        end_date,
        service_schedule,
        service_duration,
        message_to_seller,
        rejection_reason,
        transaction_status,
        is_blockchain_pending,
        rejected_at,
        blockchain_tx_hash
    ) VALUES (
        p_order_id,
        v_order.buyer_id,
        v_order.seller_id,
        v_order.product_id,
        v_category.category_id,
        COALESCE(v_buyer.first_name || ' ' || v_buyer.last_name, 'Buyer'),
        COALESCE(v_seller.first_name || ' ' || v_seller.last_name, 'Seller'),
        v_seller.phone_number,
        v_order.listing_type,
        v_category.category_name,
        v_order.product_name,
        v_order.description,
        v_order.price,
        v_order.buyer_quantity,
        v_order.pickup_location,
        v_order.meetup_location,
        v_order.return_condition,
        v_order.rental_duration,
        v_order.start_date,
        v_order.end_date,
        v_order.service_schedule,
        v_order.service_duration,
        v_order.message_to_seller,
        p_rejection_reason,
        'REJECTED',
        TRUE,
        NOW(),
        gen_random_uuid()::TEXT
    ) RETURNING transaction_id INTO v_transaction_id;
    
    -- Create notification for buyer
    INSERT INTO notifications (user_id, title, message, type, related_order_id, related_transaction_id, created_at)
    VALUES (
        v_order.buyer_id,
        'Order Rejected',
        'Your order for ' || v_order.product_name || ' has been rejected.' ||
        CASE WHEN p_rejection_reason IS NOT NULL THEN ' Reason: ' || p_rejection_reason ELSE '' END,
        'transaction',
        p_order_id,
        v_transaction_id,
        NOW()
    );
    
    RETURN v_transaction_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION reject_order IS 
    'Reject a pending order and create transaction record for blockchain processing';

-- Function: Cancel Order from Buyer Side
CREATE OR REPLACE FUNCTION cancel_order_by_buyer(
    p_order_id UUID,
    p_cancellation_reason TEXT DEFAULT NULL
)
RETURNS UUID AS $$
DECLARE
    v_transaction_id UUID;
    v_order RECORD;
    v_buyer RECORD;
    v_seller RECORD;
    v_category RECORD;
BEGIN
    -- Get order details
    SELECT * INTO v_order
    FROM order_details
    WHERE order_id = p_order_id AND order_status = 'pending';
    
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Order not found or already processed';
    END IF;
    
    -- Get buyer information
    SELECT user_id, first_name, last_name, email, phone_number 
    INTO v_buyer
    FROM users
    WHERE user_id = v_order.buyer_id;
    
    -- Get seller information
    SELECT user_id, first_name, last_name, email, phone_number 
    INTO v_seller
    FROM users
    WHERE user_id = v_order.seller_id;
    
    -- Get category information
    SELECT cat.category_id, cat.category_name 
    INTO v_category
    FROM categories cat
    INNER JOIN products p ON cat.category_id = p.category_id
    WHERE p.product_id = v_order.product_id;
    
    -- Update order status to cancelled
    UPDATE order_details
    SET 
        order_status = 'cancelled',
        cancellation_reason = p_cancellation_reason,
        updated_at = NOW()
    WHERE order_id = p_order_id;
    
    -- Create transaction record for blockchain as cancelled
    INSERT INTO transactions (
        order_id,
        buyer_id,
        seller_id,
        product_id,
        category_id,
        buyer_name,
        seller_name,
        seller_phone,
        listing_type,
        category_name,
        item_name,
        item_description,
        item_price,
        quantity,
        final_pickup_location,
        final_meetup_location,
        return_condition,
        rental_duration,
        start_date,
        end_date,
        service_schedule,
        service_duration,
        message_to_seller,
        cancellation_reason,
        transaction_status,
        is_blockchain_pending,
        cancelled_at,
        blockchain_tx_hash
    ) VALUES (
        p_order_id,
        v_order.buyer_id,
        v_order.seller_id,
        v_order.product_id,
        v_category.category_id,
        COALESCE(v_buyer.first_name || ' ' || v_buyer.last_name, 'Buyer'),
        COALESCE(v_seller.first_name || ' ' || v_seller.last_name, 'Seller'),
        v_seller.phone_number,
        v_order.listing_type,
        v_category.category_name,
        v_order.product_name,
        v_order.description,
        v_order.price,
        v_order.buyer_quantity,
        v_order.pickup_location,
        v_order.meetup_location,
        v_order.return_condition,
        v_order.rental_duration,
        v_order.start_date,
        v_order.end_date,
        v_order.service_schedule,
        v_order.service_duration,
        v_order.message_to_seller,
        p_cancellation_reason,
        'CANCELLED',
        TRUE,
        NOW(),
        gen_random_uuid()::TEXT
    ) RETURNING transaction_id INTO v_transaction_id;
    
    -- Create notification for seller
    INSERT INTO notifications (user_id, title, message, type, related_order_id, related_transaction_id, created_at)
    VALUES (
        v_order.seller_id,
        'Order Cancelled',
        'Order for ' || v_order.product_name || ' has been cancelled by buyer.' ||
        CASE WHEN p_cancellation_reason IS NOT NULL THEN ' Reason: ' || p_cancellation_reason ELSE '' END,
        'transaction',
        p_order_id,
        v_transaction_id,
        NOW()
    );
    
    RETURN v_transaction_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

COMMENT ON FUNCTION cancel_order_by_buyer IS 
    'Cancel a pending order from buyer side and create transaction record for blockchain processing';

-- =====================================================================
-- ORDER MANAGEMENT FUNCTIONS - COMPLETION MESSAGE
-- =====================================================================

DO $$
BEGIN
    RAISE NOTICE '';
    RAISE NOTICE '========================================================';
    RAISE NOTICE 'ORDER MANAGEMENT FUNCTIONS CREATED';
    RAISE NOTICE '========================================================';
    RAISE NOTICE 'Functions:';
    RAISE NOTICE '  - accept_order_and_create_transaction()';
    RAISE NOTICE '  - reject_order()';
    RAISE NOTICE '  - cancel_order_by_buyer()';
    RAISE NOTICE '';
    RAISE NOTICE 'Usage:';
    RAISE NOTICE '  SELECT accept_order_and_create_transaction(';
    RAISE NOTICE '    ''order-uuid'',';
    RAISE NOTICE '    ''Final Pickup Location'',';
    RAISE NOTICE '    ''Final Meetup Location''';
    RAISE NOTICE '  );';
    RAISE NOTICE '';
    RAISE NOTICE '  SELECT reject_order(';
    RAISE NOTICE '    ''order-uuid'',';
    RAISE NOTICE '    ''Rejection reason text''';
    RAISE NOTICE '  );';
    RAISE NOTICE '';
    RAISE NOTICE '  SELECT cancel_order_by_buyer(';
    RAISE NOTICE '    ''order-uuid'',';
    RAISE NOTICE '    ''Cancellation reason text''';
    RAISE NOTICE '  );';
    RAISE NOTICE '';
    RAISE NOTICE 'Status: ✅ Order Management Functions Ready';
    RAISE NOTICE '========================================================';
END $$;
